import React from 'react';
import s from './Public.module.css';
import Post from './Post/Post'

const Public = () => {
    return (
        <div className={s.content}>
            <img className={s.image} src={"https://static.tripzilla.com/thumb/2/8/92200_800x.jpg"}/>
            <div>
                <h1>Посты</h1>
            </div>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
            <Post message={"Всем привет! "} likes={"21"}/>
        </div>

    )
}

export default Public;